### ISSUE TITLE
it is not working in device(android), but works great on web (ionic serve)

### ISSUE THREAD

**Issue by faraazc** [idanwe/ionic-whatsapp#1]
Hi i have cloned this repo. I am not able to run this on device,
I have taken the server part out and hosted it on EC2 and modified my client side **meteor_runtime_config**.DDP_DEFAULT_CONNECTION_URL to point to EC2 instance.

With the above i am able to see app working as expected when i did ionic serve --lab

But when i built using below commands. App though installs well but it is hanging at state "sending verification code.." and never proceeds further and i see in the server request never came..

ionic platform add android
ionic build android
or
ionic run android

Any help would be highly appreciated.
I have tried even after updating ionic cli to the latest nightly build. But problem still persists

**Comment by radiegtya** [comment]
I need this too :+1:

**Comment by idanwe** [comment]
@faraazc @radiegtya I didn't test it on a device with the ionic cli.

I will try to run it tomorrow

**Comment by faraazc** [comment]
@idanwe ..Please run and provide me a solution.. Thanks a lot in advance..

**Comment by faraazc** [comment]
Hi I have resolved this issue. This issue will be seen when used with Cordova >= 5.0, because now cordova build process does not include the whitelisting plugin by default. we need add it explicitly.
below is the command to include it.

cordova plugin add https://github.com/apache/cordova-plugin-whitelist.git

**Comment by idanwe** [comment]
@faraazc good catch!
