### ISSUE TITLE
Cannot read property 'ECMAScript' of undefined

### ISSUE THREAD

**Issue by elmor34** [idanwe/ionic-whatsapp#5]
Problem with ECMAScript continues.

_Uncaught TypeError: Cannot read property 'ECMAScript' of undefined
ionic.bundle.js:13212 Uncaught Error: [$injector:modulerr] Failed to instantiate module whatsapp due to:
Error: [$injector:modulerr] Failed to instantiate module angular-meteor due to:
Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=angular-meteor
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:8895:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:10785:17_

**Comment by daengdeni** [comment]
just update angular-meteor to version 1.2
this work for me...

```
bower install angular-material --save
```

**Comment by idanwe** [comment]
@elmor34 check that you are using the latest version of angular-meteor

**Comment by elmor34** [comment]
Thanks for prompt reply. 
It worked with correcting following line in bower.json as :

**"angular-meteor": "~1.2.0",**    

Actually I did the same in just after you closed the previous issue, and it was asking 4 options,
now it's asking 3 options. And this time worked.

If you can update this in bower.json then we would not disturb you. :+1:
