### ISSUE TITLE
step 3 not clear

### ISSUE THREAD

**Issue by leizard** [idanwe/ionic-whatsapp#6]
Sorry for my silly question but in step 3 I couldn't find a way to connect to server. something like:

```
__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = "https://myserver.io"
```

Could you explain it for me ? Thank you.

**Comment by idanwe** [comment]
You need to defined the connection url variable [before require meteor-client-side](https://github.com/idanwe/ionic-whatsapp/blob/step_03/www/index.html#L14-L15)

So something like should work

``` html
<script>
  __meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = "https://myserver.io"
</script>
<script src="lib/meteor-client-side/dist/meteor-client-side.bundle.min.js"></script>
```

**Comment by leizard** [comment]
yeah it works perfectly now. Thank you for your awesome work.
