### ISSUE TITLE
How to install and run?

### ISSUE THREAD

**Issue by pbreit** [idanwe/ionic-whatsapp#8]
What are the basic steps to install and run this (on Mac OS El Cap)? Something like this?

```
git clone https://github.com/idanwe/ionic-whatsapp.git
cd ionic-whatsapp
npm install
bower install
ionic serve
```

I get various deprecation warnings (gulp-minify-css, lodash, npmconf, pangyp). node-sass seems to fail entirely. Bower doesn't find a suitable version of Angular.

When I run, the URL in address flickers a bunch on /tab/chats but leaves a white screen.

I get a bunch of console errors including:

Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:3000/sockjs/info?cb=vy2mmlzk7e Failed to load resource: net::ERR_CONNECTION_REFUSED

The ionic server throws: Error: `libsass` bindings not found. (which I assume has something to do with the node-sass install problem).

Is this the best project for the associated blog article (wonderful, btw)? I've seen a few projects and just wanted to make sure I selected one that would likely work and was continuing to get attention. Thanks.

**Comment by pbreit** [comment]
I was able to get this one to work so should be able to stick with it. Yes, the Meteor package mgmt/install does seem quite nice.

https://github.com/idanwe/meteor-whatsapp

**Comment by idanwe** [comment]
So every thing works for you now?
Can we close the issue?

**Comment by pbreit** [comment]
Well, I was able to get meteor-whatsapp to work OK but not ionic-whatsapp. I'm OK now but might be nice to have install instructions.

**Comment by idanwe** [comment]
Do you want to create PR for that?

**Comment by pbreit** [comment]
I thought about that but I'm not really sure the correct or successful way
to install. If I figure it out, I'll see what I can do.

On Wed, Jan 27, 2016 at 12:10 PM, Idan Wender notifications@github.com
wrote:

> Do you want to create PR for that?
> 
> On יום ד׳, 27 בינו׳ 2016 at 21:52 Patrick Breitenbach <
> notifications@github.com> wrote:
> 
> > Well, I was able to get meteor-whatsapp to work OK but not
> > ionic-whatsapp.
> > I'm OK now but might be nice to have install instructions.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/idanwe/ionic-whatsapp/issues/8#issuecomment-175822741>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/idanwe/ionic-whatsapp/issues/8#issuecomment-175830461
> .

## 

Patrick Breitenbach
http://linkedin.com/in/pbreitenbach
